modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="CzechPerson"
credits="Asset art by Garfungus. Inspired by DELTARUNE by Toby Fox."

# Pixel art logo - keep logoBlur off so it stays crisp in the mods screen
logoFile="forgottenman.png"
logoBlur=false

description='''
Will you forget me too?
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
